// Copyright 2024-2025, Pulumi Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package convert

var pulumiSupportedProviders = []string{
	"acme",
	"aiven",
	"akamai",
	"alicloud",
	"aquasec",
	"archive",
	"artifactory",
	"astra",
	"auth0",
	"aws",
	"aws-eksa",
	"azure",
	"azuread",
	"azuredevops",
	"buildkite",
	"cloudamqp",
	"cloudflare",
	"cloudinit",
	"cloudngfwaws",
	"concourse",
	"configcat",
	"confluentcloud",
	"consul",
	"databricks",
	"datadog",
	"dbtcloud",
	"digitalocean",
	"dnsimple",
	"docker",
	"doppler",
	"ec",
	"exoscale",
	"external",
	"f5bigip",
	"fastly",
	"gandi",
	"github",
	"github-credentials",
	"gitlab",
	"google",
	"googleworkspace",
	"harbor",
	"harness",
	"hcloud",
	"hcp",
	"heroku",
	"http",
	"ise",
	"junipermist",
	"kafka",
	"keycloak",
	"kong",
	"kubernetes",
	"linode",
	"mailgun",
	"matchbox",
	"meraki",
	"minio",
	"mongodbatlas",
	"mssql",
	"mysql",
	"newrelic",
	"ngrok",
	"nomad",
	"ns1",
	"null",
	"oci",
	"okta",
	"onelogin",
	"openstack",
	"opsgenie",
	"pagerduty",
	"postgresql",
	"purrl",
	"rabbitmq",
	"rancher2",
	"random",
	"scm",
	"sdwan",
	"sentry",
	"signalfx",
	"slack",
	"snowflake",
	"splunk",
	"spotinst",
	"statuscake",
	"sumologic",
	"tailscale",
	"tf-provider-boilerplate",
	"time",
	"tls",
	"unifi",
	"vault",
	"venafi",
	"vra",
	"vsphere",
	"wavefront",
	"xyz",
	"zitadel",
}

var pulumiProviderConfigRenames = map[string]string{
	"google": "gcp",
}
