name: Automatic Rebase
on:
  repository_dispatch:
    types: [ auto-rebase-command ]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@cf2ad5908b365d40882ef06dab959717ec1aaf71 # 1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
