name: Lint

on:
  workflow_call:
    inputs:
      commit-ref:
        description: Commit ref to check out and run tests against.
        default: ''
        required: false
        type: string

permissions: read-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    container: golangci/golangci-lint:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - run: go mod tidy
      - name: Fail if go.mod not tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error go.mod not tidy"
            exit 1
          fi

      # We leverage the golangci-lint action to install and maintain the cache, but we want to run the command
      # ourselves. The action doesn't have an install-only mode, so we'll ask it to print its help output instead.
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --help

      - name: Lint
        env:
          GOFLAGS: "-buildvcs=false"
        run: make lint GOLANGCI_LINT_ARGS=--out-format=colored-line-number
