name: Publish

on:
  workflow_call:
    inputs:
      goreleaser-args:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags || true
      - name: Install Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
      - name: Install tools via mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2
        with:
          args: ${{ inputs.goreleaser-args }}
          version: latest
