name: Lint

on:
  workflow_call:
    inputs:
      commit-ref:
        description: Commit ref to check out and run tests against.
        default: ''
        required: false
        type: string

permissions: read-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install tools via mise
        uses: jdx/mise-action@v2

      - run: go mod tidy
      - name: Fail if go.mod not tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error go.mod not tidy"
            exit 1
          fi

      - name: Lint
        env:
          GOFLAGS: "-buildvcs=false"
        run: make lint
