name: Test

on:
  workflow_call:
    inputs:
      live-test:
        description: |
          Whether to run tests against a live environment. When false, tests that require secrets
          should be skipped.
        default: false
        required: false
        type: boolean
      commit-ref:
        description: Commit ref to check out and run tests against.
        default: ''
        required: false
        type: string
    secrets:
      PULUMI_ACCESS_TOKEN:   { required: false }
      AWS_ACCESS_KEY_ID:     { required: false }
      AWS_SECRET_ACCESS_KEY: { required: false }
      AWS_CI_ROLE_ARN:       { required: false }
      ARM_CLIENT_ID:         { required: false }
      ARM_CLIENT_SECRET:     { required: false }
      ARM_SUBSCRIPTION_ID:   { required: false }
      ARM_TENANT_ID:         { required: false }
      CODECOV_TOKEN:         { required: false }


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commit-ref }}

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install tools via mise
        uses: jdx/mise-action@v2

      - name: Install pulumi plugins
        run: |
          pulumi plugin install resource aws
          pulumi plugin install resource azure
          pulumi plugin install resource gcp
          pulumi plugin install resource kubernetes
          pulumi plugin install resource random
          pulumi plugin install resource std

      - name: Build and install
        run: make install

      - name: Test
        run: |
          set -euo pipefail
          go test -v -coverprofile=coverage.out -timeout 2h -parallel 10 ./... 2>&1 | tee /tmp/gotest.log

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          files: coverage.out
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
